# Generated by Django 4.1.1 on 2022-09-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='emailid',
        ),
    ]
